### ISSUE TITLE
Add <categories> in appdata.xml

### ISSUE THREAD

**Issue by jgarciao** [flathub/com.github.miguelmota.Cointop#1]
I'm not 100% sure but I think the command line instructions are [not working well for your app](https://github.com/flathub/linux-store-frontend/issues/108) because of missing `<categories>` in the appdata file

I will fix the webapp to be immune to this but could you add a `<categories>` section in [this file](https://github.com/miguelmota/cointop/blob/master/flathub/com.github.miguelmota.Cointop.appdata.xml) and rebuild your app in the meantime?

More info at https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-categories

**Comment by miguelmota** [comment]
Added category section

**Comment by jgarciao** [comment]
Thanks Miguel!
